version: '3.5'
services:
  anycontent-client-php72:
    container_name: anycontent-client-php72
    build:
      context: ./build/php
      dockerfile: Dockerfile
    image: anycontent-client-php72:1.0.0
    volumes:
      - ./config/php/php.ini:/usr/local/etc/php/php.ini:cached
      - ../../:/application:cached
    environment:
      PHPUNIT_RESTLIKE_URI: http://anycontent-repository-service-php72/1/phpunit
    networks:
      - anycontent
  #anycontent-client-phpunit-mysql: see php70 docker setup
networks:
  anycontent:
    driver: "bridge"
    name: "anycontent"