version: '3.5'
services:
  anycontent-client-php70:
    container_name: anycontent-client-php70
    build:
      context: ./build/php
      dockerfile: Dockerfile
    image: anycontent-client-php70:1.0.0
    volumes:
      - ./config/php/php.ini:/usr/local/etc/php/php.ini:cached
      - ../../:/application:cached
    environment:
      PHPUNIT_RESTLIKE_URI: http://anycontent-repository-service-php70/1/phpunit
    networks:
      - anycontent
  anycontent-client-phpunit-mysql:
    container_name: anycontent-client-phpunit-mysql
    image: mysql:5.7
    ports:
      - "8199:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
     - anycontent
networks:
  anycontent:
    driver: "bridge"
    name: "anycontent"
